export const RECIPES = [
  {
    id: 0,
    name: "Indian Chicken Tikka Masala",
    image: "/assets/images/image1.jpg",
    featured: true,
    preparationTime: "00:30",
    cookingTime: "03:40",
    yields: "5 Servings",
  },
  {
    id: 1,
    name: "Nepali Style Chicken Curry",
    image: "/assets/images/image2.jpg",
    featured: true,
    preparationTime: "00:20",
    cookingTime: "00:30",
    yields: "4-6 Servings",
  },
  {
    id: 2,
    name: "Iranian Noodle Soup",
    image: "/assets/images/image3.jpg",
    featured: true,
    preparationTime: "00:30",
    cookingTime: "03:40",
    yields: "5 Servings",
  },
  {
    id: 3,
    name: "Chinese Fried Rice",
    image: "/assets/images/image3.jpg",
    featured: false,
    preparationTime: "00:30",
    cookingTime: "00:40",
    yields: "5 Servings",
  },
];
